
import { UserRole } from '../types';

export type Permission =
    | 'VIEW_DASHBOARD'
    | 'MANAGE_MENUS'
    | 'APPROVE_MENUS'
    | 'VIEW_MENUS'
    | 'MANAGE_STOCK'
    | 'VIEW_STOCK'
    | 'EXECUTE_MENU'
    | 'MANAGE_STUDENTS'
    | 'VIEW_STUDENTS_SENSITIVE' // Health data, CPF
    | 'MANAGE_USERS'
    | 'VIEW_REPORTS_ADMIN'
    | 'VIEW_REPORTS_TECHNICAL'
    | 'MANAGE_PROCUREMENT'
    | 'VIEW_PROCUREMENT'
    | 'MANAGE_SCHOOLS'
    | 'MANAGE_STAFF'
    | 'MANAGE_SYSTEM_SETTINGS'
    | 'VIEW_LOGS'
    | 'MANAGE_BACKUP'
    | 'MANAGE_DISTRIBUTION'
    | 'VIEW_DISTRIBUTIONS'
    | 'RECEIVE_DISTRIBUTION'
    | 'MANAGE_STUDENTS_IMPORT'
    | 'EXECUTE_STOCK_AUDIT'
    | 'REQUEST_STOCK_REPLENISHMENT'
    | 'MANAGE_REPLENISHMENT_REQUESTS'
    | 'REVIEW_REPLENISHMENT_NUTRI'
    | 'USE_NUTRITIONAL_SIMULATOR'
    | 'VIEW_RISK_INDICATORS'
    | 'MANAGE_PREVENTIVE_REPORTS';

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
    [UserRole.ADMIN]: [
        'VIEW_DASHBOARD', 'MANAGE_MENUS', 'APPROVE_MENUS', 'VIEW_MENUS',
        'MANAGE_STOCK', 'VIEW_STOCK', 'MANAGE_STUDENTS', 'VIEW_STUDENTS_SENSITIVE',
        'MANAGE_USERS', 'VIEW_REPORTS_ADMIN', 'VIEW_REPORTS_TECHNICAL',
        'MANAGE_PROCUREMENT', 'VIEW_PROCUREMENT', 'MANAGE_SCHOOLS', 'MANAGE_STAFF',
        'MANAGE_SYSTEM_SETTINGS', 'VIEW_LOGS', 'MANAGE_BACKUP',
        'MANAGE_DISTRIBUTION', 'VIEW_DISTRIBUTIONS', 'RECEIVE_DISTRIBUTION',
        'MANAGE_STUDENTS_IMPORT', 'EXECUTE_STOCK_AUDIT', 'REQUEST_STOCK_REPLENISHMENT',
        'MANAGE_REPLENISHMENT_REQUESTS', 'REVIEW_REPLENISHMENT_NUTRI', 'USE_NUTRITIONAL_SIMULATOR',
        'VIEW_RISK_INDICATORS', 'MANAGE_PREVENTIVE_REPORTS'
    ],
    [UserRole.NUTRICIONISTA]: [
        'VIEW_DASHBOARD', 'MANAGE_MENUS', 'APPROVE_MENUS', 'VIEW_MENUS',
        'MANAGE_STOCK', 'VIEW_STOCK', 'MANAGE_STUDENTS', 'VIEW_STUDENTS_SENSITIVE',
        'VIEW_REPORTS_ADMIN', 'VIEW_REPORTS_TECHNICAL', 'MANAGE_PROCUREMENT', 'VIEW_PROCUREMENT',
        'MANAGE_SCHOOLS', 'MANAGE_STAFF', 'MANAGE_DISTRIBUTION', 'VIEW_DISTRIBUTIONS',
        'EXECUTE_STOCK_AUDIT', 'REVIEW_REPLENISHMENT_NUTRI', 'USE_NUTRITIONAL_SIMULATOR',
        'VIEW_RISK_INDICATORS', 'MANAGE_PREVENTIVE_REPORTS'
    ],
    [UserRole.COORDENADORA]: [
        'VIEW_DASHBOARD', 'VIEW_MENUS', 'APPROVE_MENUS', 'VIEW_STOCK',
        'VIEW_STUDENTS_SENSITIVE', 'VIEW_REPORTS_ADMIN', 'VIEW_REPORTS_TECHNICAL',
        'VIEW_PROCUREMENT', 'VIEW_RISK_INDICATORS'
    ],
    [UserRole.SECRETARIO]: [
        'VIEW_DASHBOARD', 'VIEW_MENUS', 'APPROVE_MENUS', 'VIEW_REPORTS_ADMIN',
        'VIEW_PROCUREMENT', 'VIEW_RISK_INDICATORS'
    ],
    [UserRole.DIRETOR]: [
        'VIEW_DASHBOARD', 'VIEW_MENUS', 'VIEW_STOCK', 'VIEW_REPORTS_TECHNICAL',
        'RECEIVE_DISTRIBUTION', 'VIEW_DISTRIBUTIONS', 'MANAGE_STUDENTS', 'VIEW_STUDENTS_SENSITIVE',
        'EXECUTE_STOCK_AUDIT', 'REQUEST_STOCK_REPLENISHMENT'
    ],
    [UserRole.TECNICO]: [
        'VIEW_DASHBOARD', 'VIEW_MENUS', 'MANAGE_STOCK', 'VIEW_STOCK',
        'VIEW_REPORTS_TECHNICAL', 'MANAGE_REPLENISHMENT_REQUESTS'
    ],
    [UserRole.MERENDEIRA]: [
        'VIEW_MENUS', 'EXECUTE_MENU', 'VIEW_STOCK', 'VIEW_DISTRIBUTIONS'
    ],
    [UserRole.SECRETARIA]: [
        'VIEW_DASHBOARD', 'VIEW_MENUS', 'APPROVE_MENUS', 'VIEW_REPORTS_ADMIN',
        'VIEW_PROCUREMENT', 'USE_NUTRITIONAL_SIMULATOR', 'VIEW_RISK_INDICATORS'
    ],
    [UserRole.VISUALIZADOR]: [
        'VIEW_DASHBOARD', 'VIEW_MENUS', 'VIEW_STOCK'
    ],
    [UserRole.NUCLEO_ESCOLAR]: [
        'VIEW_DASHBOARD', 'VIEW_MENUS', 'VIEW_STOCK', 'VIEW_REPORTS_TECHNICAL',
        'RECEIVE_DISTRIBUTION', 'VIEW_DISTRIBUTIONS', 'MANAGE_STUDENTS', 'VIEW_STUDENTS_SENSITIVE',
        'EXECUTE_STOCK_AUDIT', 'REQUEST_STOCK_REPLENISHMENT', 'MANAGE_STUDENTS_IMPORT',
        'VIEW_RISK_INDICATORS'
    ]
};

export const hasPermission = (role: UserRole | undefined, permission: Permission): boolean => {
    if (!role) return false;
    return ROLE_PERMISSIONS[role]?.includes(permission) || false;
};

export const canEditSensitiveData = (role: UserRole | undefined): boolean => {
    return role === UserRole.ADMIN || role === UserRole.NUTRICIONISTA;
};
